"""Add Kevin Bacon rule fields to RSVP

Revision ID: 74aa414e8614
Revises: b2a814f22dfe
Create Date: 2025-10-26 21:04:32.502836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74aa414e8614'
down_revision: Union[str, None] = 'b2a814f22dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('degree', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('invited_by_rsvp_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invitation_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('has_sent_invitation', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.drop_column('has_sent_invitation')
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('invitation_code')
        batch_op.drop_column('invited_by_rsvp_id')
        batch_op.drop_column('degree')
    # ### end Alembic commands ###
